apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service.yaml
  - service-account.yaml
  - runner-config.yaml
  - statefulset.yaml
  - cleanup-lifecycle.yaml
