apiVersion: v1
kind: Service
metadata:
  name: gitea-runner
  namespace: gitea-runners
  labels:
    app.kubernetes.io/name: gitea-runner
    app.kubernetes.io/part-of: gitea-actions
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: gitea-runner
  ports:
    - name: cache
      port: 8088
      targetPort: cache
