apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea-runner
  namespace: gitea-runners
  labels:
    app.kubernetes.io/name: gitea-runner
    app.kubernetes.io/part-of: gitea-actions
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitea-runner
  namespace: gitea-runners
  labels:
    app.kubernetes.io/name: gitea-runner
    app.kubernetes.io/part-of: gitea-actions
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitea-runner
  namespace: gitea-runners
  labels:
    app.kubernetes.io/name: gitea-runner
    app.kubernetes.io/part-of: gitea-actions
subjects:
  - kind: ServiceAccount
    name: gitea-runner
    namespace: gitea-runners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitea-runner
