keys:
  - &snuff             age1w4hw2ntxrtfqhht63s9lf7nhjxjmdcc927hndn5ygcqqj532qssq4m2m6p
  - &yukkop            age1r25zdeqq8nac6dgca9en28r57ffyz9u9d8z5yc25gc8xqz747vaqmdtk0h
  - &yukkop-alt        age1vv46vn4hsn2lg6jy834cpu40c3mvqklldcm3hjtynrhwtpmlpc8szruz4v
  - &nrv               age1x04u7ftjgx8de2gq596e7frauze764cmn7jjwqnx8szthvfft5qq0tezx6
  - &bfs-server        age15yzgmsvl3ku2w863h6gw2vpmw37m9aruv6xrj4fue6n2jpm7pyuqk9xjmj
  - &bfs-pol-server    age1fpytf05sg9n6ywpwkmn09lhpfvgtud9h75h76jhxha475zpnasqq952rpu
  - &neuro-server      age15yzgmsvl3ku2w863h6gw2vpmw37m9aruv6xrj4fue6n2jpm7pyuqk9xjmj
  - &games-server      age15yzgmsvl3ku2w863h6gw2vpmw37m9aruv6xrj4fue6n2jpm7pyuqk9xjmj
  - &hectic-lab-server age13h8twnwvgxn04l5ywtru89a6psw5d0uckr2eghxsjp88a5augvsstq5ard
  - &umbriel-bfs       age1jxntjca8q2vxvf2jaal4xyvm2ae6sh62fhv897694kuzawfrk5asj00zdt

creation_rules:
  - path_regex: sus/home.xray.yaml$
    key_groups:
      - age:
        - *yukkop

  - path_regex: sus/bfs.xray.yaml$
    key_groups:
      - age:
        - *snuff
        - *yukkop
        - *bfs-server
        - *bfs-pol-server

  - path_regex: sus/neuro.yaml$
    key_groups:
      - age:
        - *yukkop
        - *neuro-server

  - path_regex: sus/games.yaml$
    key_groups:
      - age:
        - *yukkop
        - *games-server

  - path_regex: sus/hectic-lab.yaml$
    key_groups:
      - age:
        - *nrv
        - *yukkop
        - *yukkop-alt
        - *hectic-lab-server
        - *umbriel-bfs
