keys:
  - &snuff        age1w4hw2ntxrtfqhht63s9lf7nhjxjmdcc927hndn5ygcqqj532qssq4m2m6p
  - &yukkop       age1r25zdeqq8nac6dgca9en28r57ffyz9u9d8z5yc25gc8xqz747vaqmdtk0h
  - &bfs-server   age15yzgmsvl3ku2w863h6gw2vpmw37m9aruv6xrj4fue6n2jpm7pyuqk9xjmj
  - &neuro-server age15yzgmsvl3ku2w863h6gw2vpmw37m9aruv6xrj4fue6n2jpm7pyuqk9xjmj

creation_rules:
  - path_regex: sus/home.xray.yaml$
    key_groups:
      - age:
        - *yukkop

  - path_regex: sus/bfs.xray.yaml$
    key_groups:
      - age:
        - *snuff
        - *yukkop
        - *bfs-server

  - path_regex: sus/neuro.yaml$
    key_groups:
      - age:
        - *yukkop
        - *neuro-server
