[package]
name = "prettify-log"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.217"
serde_json = "1.0.138"

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.3"
float-cmp = "0.10.0"
tempfile = "3.16.0"

[[test]]
name = "test_prettify"
path = "test/prettify.rs"
