[package]
name = "pg-schema"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
env_logger = "0.11.5"
hex = "0.4.3"
log = "0.4.22"
postgres = "0.19.9"
regex = "1.11.1"
sha2 = "0.10.8"
uuid = "1.11.0"
which = "7.0.0"

[workspace]
