/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 33
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 28
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACE_LBRACK = 1,
  anon_sym_RBRACK_RBRACE = 2,
  anon_sym_for = 3,
  anon_sym_in = 4,
  anon_sym_done = 5,
  anon_sym_DOT = 6,
  anon_sym_LBRACK = 7,
  aux_sym_index_token1 = 8,
  aux_sym_index_token2 = 9,
  aux_sym_index_token3 = 10,
  aux_sym_index_token4 = 11,
  anon_sym_RBRACK = 12,
  aux_sym_string_token1 = 13,
  aux_sym_string_token2 = 14,
  sym_text = 15,
  sym_source_file = 16,
  sym_element = 17,
  sym_interpolation = 18,
  sym_segment = 19,
  sym_for = 20,
  sym_done = 21,
  sym_actual_bracket = 22,
  sym_path = 23,
  sym_index = 24,
  sym_string = 25,
  aux_sym_source_file_repeat1 = 26,
  aux_sym_path_repeat1 = 27,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE_LBRACK] = "{[",
  [anon_sym_RBRACK_RBRACE] = "]}",
  [anon_sym_for] = "for",
  [anon_sym_in] = "in",
  [anon_sym_done] = "done",
  [anon_sym_DOT] = ".",
  [anon_sym_LBRACK] = "[",
  [aux_sym_index_token1] = "index_token1",
  [aux_sym_index_token2] = "index_token2",
  [aux_sym_index_token3] = "index_token3",
  [aux_sym_index_token4] = "index_token4",
  [anon_sym_RBRACK] = "]",
  [aux_sym_string_token1] = "string_token1",
  [aux_sym_string_token2] = "string_token2",
  [sym_text] = "text",
  [sym_source_file] = "source_file",
  [sym_element] = "element",
  [sym_interpolation] = "interpolation",
  [sym_segment] = "segment",
  [sym_for] = "for",
  [sym_done] = "done",
  [sym_actual_bracket] = "actual_bracket",
  [sym_path] = "path",
  [sym_index] = "index",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_path_repeat1] = "path_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE_LBRACK] = anon_sym_LBRACE_LBRACK,
  [anon_sym_RBRACK_RBRACE] = anon_sym_RBRACK_RBRACE,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_done] = anon_sym_done,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [aux_sym_index_token1] = aux_sym_index_token1,
  [aux_sym_index_token2] = aux_sym_index_token2,
  [aux_sym_index_token3] = aux_sym_index_token3,
  [aux_sym_index_token4] = aux_sym_index_token4,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_text] = sym_text,
  [sym_source_file] = sym_source_file,
  [sym_element] = sym_element,
  [sym_interpolation] = sym_interpolation,
  [sym_segment] = sym_segment,
  [sym_for] = sym_for,
  [sym_done] = sym_done,
  [sym_actual_bracket] = sym_actual_bracket,
  [sym_path] = sym_path,
  [sym_index] = sym_index,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_path_repeat1] = aux_sym_path_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_done] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_index_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_index_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_index_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_index_token4] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [sym_segment] = {
    .visible = true,
    .named = true,
  },
  [sym_for] = {
    .visible = true,
    .named = true,
  },
  [sym_done] = {
    .visible = true,
    .named = true,
  },
  [sym_actual_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym_index] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_path_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
};

static const TSCharacterRange aux_sym_string_token1_character_set_1[] = {
  {0, 0x08}, {0x0b, '\f'}, {0x0e, 0x1f}, {'!', '!'}, {'#', '-'}, {'/', 'Z'}, {'^', 'z'}, {'|', '|'},
  {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(20);
      ADVANCE_MAP(
        '"', 5,
        '-', 17,
        '.', 26,
        '0', 28,
        '[', 27,
        ']', 34,
        'd', 14,
        'f', 13,
        'i', 11,
        '{', 7,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '.') ADVANCE(26);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == 'd') ADVANCE(41);
      if (lookahead == 'f') ADVANCE(42);
      if (lookahead == '{') ADVANCE(7);
      if (lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead != 0 &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '}') ADVANCE(44);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '.') ADVANCE(26);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == 'f') ADVANCE(42);
      if (lookahead == '{') ADVANCE(7);
      if (lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(36);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0 &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '}') ADVANCE(44);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '.') ADVANCE(26);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (lookahead != 0 &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(44);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (lookahead != 0 &&
          lookahead != '.' &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(44);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(45);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '.') ADVANCE(26);
      if (lookahead == ']') ADVANCE(16);
      if (lookahead == 'i') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      END_STATE();
    case 7:
      if (lookahead == '[') ADVANCE(21);
      END_STATE();
    case 8:
      if (lookahead == '[') ADVANCE(21);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 9:
      if (lookahead == ']') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 11:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 13:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 14:
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 16:
      if (lookahead == '}') ADVANCE(22);
      END_STATE();
    case 17:
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 18:
      if (lookahead != 0 &&
          lookahead != '[') ADVANCE(47);
      END_STATE();
    case 19:
      if (eof) ADVANCE(20);
      if (lookahead == '{') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACK);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RBRACK_RBRACE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_done);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_index_token1);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_index_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_index_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_index_token3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_index_token4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      if (lookahead == '}') ADVANCE(22);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '.') ADVANCE(26);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == 'd') ADVANCE(41);
      if (lookahead == 'f') ADVANCE(42);
      if (lookahead == '{') ADVANCE(7);
      if (lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '}') ADVANCE(44);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '.') ADVANCE(26);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == 'f') ADVANCE(42);
      if (lookahead == '{') ADVANCE(7);
      if (lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(36);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0 &&
          lookahead != '"' &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '}') ADVANCE(44);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '.') ADVANCE(26);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (lookahead != 0 &&
          lookahead != '"' &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(44);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '.' &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(44);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == 'e') ADVANCE(25);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 9, lookahead))) ADVANCE(44);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == 'n') ADVANCE(39);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 9, lookahead))) ADVANCE(44);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == 'o') ADVANCE(40);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 9, lookahead))) ADVANCE(44);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == 'o') ADVANCE(43);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 9, lookahead))) ADVANCE(44);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == 'r') ADVANCE(23);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 9, lookahead))) ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 9, lookahead))) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '"') ADVANCE(5);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '{') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 19},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 19},
  [4] = {.lex_state = 19},
  [5] = {.lex_state = 19},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 19},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 19},
  [12] = {.lex_state = 19},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 19},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 19},
  [19] = {.lex_state = 6},
  [20] = {.lex_state = 19},
  [21] = {.lex_state = 19},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 6},
  [24] = {.lex_state = 19},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 6},
  [27] = {.lex_state = 6},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 9},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 6},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK_RBRACE] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_done] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [aux_sym_index_token1] = ACTIONS(1),
    [aux_sym_index_token2] = ACTIONS(1),
    [aux_sym_index_token3] = ACTIONS(1),
    [aux_sym_index_token4] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [aux_sym_string_token2] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(28),
    [sym_element] = STATE(5),
    [sym_interpolation] = STATE(11),
    [sym_segment] = STATE(11),
    [sym_for] = STATE(4),
    [sym_actual_bracket] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE_LBRACK] = ACTIONS(5),
    [sym_text] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(9), 1,
      anon_sym_LBRACE_LBRACK,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_done,
    ACTIONS(15), 1,
      anon_sym_DOT,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    STATE(26), 1,
      sym_path,
    ACTIONS(19), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    STATE(15), 2,
      sym_index,
      sym_string,
  [27] = 6,
    ACTIONS(7), 1,
      sym_text,
    ACTIONS(21), 1,
      anon_sym_LBRACE_LBRACK,
    STATE(4), 1,
      sym_for,
    STATE(21), 1,
      sym_done,
    STATE(7), 2,
      sym_element,
      aux_sym_source_file_repeat1,
    STATE(11), 3,
      sym_interpolation,
      sym_segment,
      sym_actual_bracket,
  [49] = 6,
    ACTIONS(7), 1,
      sym_text,
    ACTIONS(21), 1,
      anon_sym_LBRACE_LBRACK,
    STATE(4), 1,
      sym_for,
    STATE(12), 1,
      sym_done,
    STATE(3), 2,
      sym_element,
      aux_sym_source_file_repeat1,
    STATE(11), 3,
      sym_interpolation,
      sym_segment,
      sym_actual_bracket,
  [71] = 6,
    ACTIONS(5), 1,
      anon_sym_LBRACE_LBRACK,
    ACTIONS(7), 1,
      sym_text,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      sym_for,
    STATE(7), 2,
      sym_element,
      aux_sym_source_file_repeat1,
    STATE(11), 3,
      sym_interpolation,
      sym_segment,
      sym_actual_bracket,
  [93] = 7,
    ACTIONS(9), 1,
      anon_sym_LBRACE_LBRACK,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(15), 1,
      anon_sym_DOT,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    STATE(26), 1,
      sym_path,
    ACTIONS(19), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    STATE(15), 2,
      sym_index,
      sym_string,
  [117] = 6,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      anon_sym_LBRACE_LBRACK,
    ACTIONS(30), 1,
      sym_text,
    STATE(4), 1,
      sym_for,
    STATE(7), 2,
      sym_element,
      aux_sym_source_file_repeat1,
    STATE(11), 3,
      sym_interpolation,
      sym_segment,
      sym_actual_bracket,
  [139] = 5,
    ACTIONS(15), 1,
      anon_sym_DOT,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    STATE(32), 1,
      sym_path,
    ACTIONS(19), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    STATE(15), 2,
      sym_index,
      sym_string,
  [157] = 3,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    STATE(23), 2,
      sym_index,
      sym_string,
  [169] = 1,
    ACTIONS(33), 4,
      aux_sym_index_token1,
      aux_sym_index_token2,
      aux_sym_index_token3,
      aux_sym_index_token4,
  [176] = 2,
    ACTIONS(37), 1,
      anon_sym_LBRACE_LBRACK,
    ACTIONS(35), 2,
      ts_builtin_sym_end,
      sym_text,
  [184] = 2,
    ACTIONS(41), 1,
      anon_sym_LBRACE_LBRACK,
    ACTIONS(39), 2,
      ts_builtin_sym_end,
      sym_text,
  [192] = 1,
    ACTIONS(43), 3,
      anon_sym_RBRACK_RBRACE,
      anon_sym_in,
      anon_sym_DOT,
  [198] = 3,
    ACTIONS(19), 1,
      aux_sym_string_token2,
    ACTIONS(45), 1,
      aux_sym_string_token1,
    STATE(31), 1,
      sym_string,
  [208] = 3,
    ACTIONS(47), 1,
      anon_sym_RBRACK_RBRACE,
    ACTIONS(49), 1,
      anon_sym_DOT,
    STATE(19), 1,
      aux_sym_path_repeat1,
  [218] = 2,
    ACTIONS(53), 1,
      anon_sym_LBRACE_LBRACK,
    ACTIONS(51), 2,
      ts_builtin_sym_end,
      sym_text,
  [226] = 3,
    ACTIONS(55), 1,
      anon_sym_RBRACK_RBRACE,
    ACTIONS(57), 1,
      anon_sym_DOT,
    STATE(17), 1,
      aux_sym_path_repeat1,
  [236] = 2,
    ACTIONS(62), 1,
      anon_sym_LBRACE_LBRACK,
    ACTIONS(60), 2,
      ts_builtin_sym_end,
      sym_text,
  [244] = 3,
    ACTIONS(49), 1,
      anon_sym_DOT,
    ACTIONS(64), 1,
      anon_sym_RBRACK_RBRACE,
    STATE(17), 1,
      aux_sym_path_repeat1,
  [254] = 2,
    ACTIONS(68), 1,
      anon_sym_LBRACE_LBRACK,
    ACTIONS(66), 2,
      ts_builtin_sym_end,
      sym_text,
  [262] = 2,
    ACTIONS(72), 1,
      anon_sym_LBRACE_LBRACK,
    ACTIONS(70), 2,
      ts_builtin_sym_end,
      sym_text,
  [270] = 1,
    ACTIONS(74), 2,
      anon_sym_RBRACK_RBRACE,
      anon_sym_DOT,
  [275] = 1,
    ACTIONS(55), 2,
      anon_sym_RBRACK_RBRACE,
      anon_sym_DOT,
  [280] = 2,
    ACTIONS(76), 1,
      anon_sym_LBRACE_LBRACK,
    ACTIONS(78), 1,
      sym_text,
  [287] = 1,
    ACTIONS(80), 1,
      anon_sym_RBRACK_RBRACE,
  [291] = 1,
    ACTIONS(82), 1,
      anon_sym_RBRACK_RBRACE,
  [295] = 1,
    ACTIONS(47), 1,
      anon_sym_RBRACK_RBRACE,
  [299] = 1,
    ACTIONS(84), 1,
      ts_builtin_sym_end,
  [303] = 1,
    ACTIONS(86), 1,
      anon_sym_RBRACK,
  [307] = 1,
    ACTIONS(88), 1,
      anon_sym_RBRACK_RBRACE,
  [311] = 1,
    ACTIONS(90), 1,
      anon_sym_in,
  [315] = 1,
    ACTIONS(92), 1,
      anon_sym_RBRACK_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 27,
  [SMALL_STATE(4)] = 49,
  [SMALL_STATE(5)] = 71,
  [SMALL_STATE(6)] = 93,
  [SMALL_STATE(7)] = 117,
  [SMALL_STATE(8)] = 139,
  [SMALL_STATE(9)] = 157,
  [SMALL_STATE(10)] = 169,
  [SMALL_STATE(11)] = 176,
  [SMALL_STATE(12)] = 184,
  [SMALL_STATE(13)] = 192,
  [SMALL_STATE(14)] = 198,
  [SMALL_STATE(15)] = 208,
  [SMALL_STATE(16)] = 218,
  [SMALL_STATE(17)] = 226,
  [SMALL_STATE(18)] = 236,
  [SMALL_STATE(19)] = 244,
  [SMALL_STATE(20)] = 254,
  [SMALL_STATE(21)] = 262,
  [SMALL_STATE(22)] = 270,
  [SMALL_STATE(23)] = 275,
  [SMALL_STATE(24)] = 280,
  [SMALL_STATE(25)] = 287,
  [SMALL_STATE(26)] = 291,
  [SMALL_STATE(27)] = 295,
  [SMALL_STATE(28)] = 299,
  [SMALL_STATE(29)] = 303,
  [SMALL_STATE(30)] = 307,
  [SMALL_STATE(31)] = 311,
  [SMALL_STATE(32)] = 315,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_segment, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_segment, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_actual_bracket, 3, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_actual_bracket, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_done, 3, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_done, 3, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_segment, 3, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_segment, 3, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_index, 3, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_for, 6, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for, 6, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [84] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_hemar(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "hemar",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
