/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 28
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 20
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACE_LBRACK = 1,
  anon_sym_RBRACK_RBRACE = 2,
  anon_sym_for = 3,
  anon_sym_in = 4,
  anon_sym_done = 5,
  anon_sym_DOT = 6,
  aux_sym_string_token1 = 7,
  aux_sym_string_token2 = 8,
  sym_text = 9,
  sym_source_file = 10,
  sym_element = 11,
  sym_interpolation = 12,
  sym_segment = 13,
  sym_for = 14,
  sym_done = 15,
  sym_path = 16,
  sym_string = 17,
  aux_sym_source_file_repeat1 = 18,
  aux_sym_path_repeat1 = 19,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE_LBRACK] = "{[",
  [anon_sym_RBRACK_RBRACE] = "]}",
  [anon_sym_for] = "for",
  [anon_sym_in] = "in",
  [anon_sym_done] = "done",
  [anon_sym_DOT] = ".",
  [aux_sym_string_token1] = "string_token1",
  [aux_sym_string_token2] = "string_token2",
  [sym_text] = "text",
  [sym_source_file] = "source_file",
  [sym_element] = "element",
  [sym_interpolation] = "interpolation",
  [sym_segment] = "segment",
  [sym_for] = "for",
  [sym_done] = "done",
  [sym_path] = "path",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_path_repeat1] = "path_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE_LBRACK] = anon_sym_LBRACE_LBRACK,
  [anon_sym_RBRACK_RBRACE] = anon_sym_RBRACK_RBRACE,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_done] = anon_sym_done,
  [anon_sym_DOT] = anon_sym_DOT,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_text] = sym_text,
  [sym_source_file] = sym_source_file,
  [sym_element] = sym_element,
  [sym_interpolation] = sym_interpolation,
  [sym_segment] = sym_segment,
  [sym_for] = sym_for,
  [sym_done] = sym_done,
  [sym_path] = sym_path,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_path_repeat1] = aux_sym_path_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_done] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [sym_segment] = {
    .visible = true,
    .named = true,
  },
  [sym_for] = {
    .visible = true,
    .named = true,
  },
  [sym_done] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_path_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == ']') ADVANCE(14);
      if (lookahead == 'd') ADVANCE(12);
      if (lookahead == 'f') ADVANCE(11);
      if (lookahead == 'i') ADVANCE(9);
      if (lookahead == '{') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == ' ') SKIP(1);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == 'd') ADVANCE(30);
      if (lookahead == 'f') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\\' &&
          lookahead != ']') ADVANCE(33);
      END_STATE();
    case 2:
      if (lookahead == ' ') SKIP(2);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == 'f') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\\' &&
          lookahead != ']') ADVANCE(33);
      END_STATE();
    case 3:
      if (lookahead == ' ') SKIP(3);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '.') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\\' &&
          lookahead != ']') ADVANCE(33);
      END_STATE();
    case 4:
      if (lookahead == ' ') SKIP(4);
      if (lookahead == '"') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '.' &&
          lookahead != '\\' &&
          lookahead != ']') ADVANCE(33);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(34);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '[') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == '[') ADVANCE(18);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 9:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 10:
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 11:
      if (lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 12:
      if (lookahead == 'o') ADVANCE(10);
      END_STATE();
    case 13:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 14:
      if (lookahead == '}') ADVANCE(19);
      END_STATE();
    case 15:
      if (lookahead != 0 &&
          lookahead != '[') ADVANCE(36);
      END_STATE();
    case 16:
      if (eof) ADVANCE(17);
      if (lookahead == '{') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACK);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACK_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_done);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == ' ') SKIP(1);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == 'd') ADVANCE(30);
      if (lookahead == 'f') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != ']') ADVANCE(33);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == ' ') SKIP(2);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == 'f') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != ']') ADVANCE(33);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == ' ') SKIP(3);
      if (lookahead == '.') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != ']') ADVANCE(33);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == ' ') SKIP(4);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '.' &&
          lookahead != '\\' &&
          lookahead != ']') ADVANCE(33);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == 'e') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '.' &&
          lookahead != '\\' &&
          lookahead != ']') ADVANCE(33);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == 'n') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '.' &&
          lookahead != '\\' &&
          lookahead != ']') ADVANCE(33);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == 'o') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '.' &&
          lookahead != '\\' &&
          lookahead != ']') ADVANCE(33);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == 'o') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '.' &&
          lookahead != '\\' &&
          lookahead != ']') ADVANCE(33);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == 'r') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '.' &&
          lookahead != '\\' &&
          lookahead != ']') ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '.' &&
          lookahead != '\\' &&
          lookahead != ']') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '"') ADVANCE(5);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '{') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 16},
  [2] = {.lex_state = 16},
  [3] = {.lex_state = 16},
  [4] = {.lex_state = 16},
  [5] = {.lex_state = 16},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 16},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 16},
  [14] = {.lex_state = 16},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 16},
  [18] = {.lex_state = 16},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 16},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK_RBRACE] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_done] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [aux_sym_string_token2] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(24),
    [sym_element] = STATE(3),
    [sym_interpolation] = STATE(10),
    [sym_segment] = STATE(10),
    [sym_for] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE_LBRACK] = ACTIONS(5),
    [sym_text] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(7), 1,
      sym_text,
    ACTIONS(9), 1,
      anon_sym_LBRACE_LBRACK,
    STATE(2), 1,
      sym_for,
    STATE(13), 1,
      sym_done,
    STATE(4), 2,
      sym_element,
      aux_sym_source_file_repeat1,
    STATE(10), 2,
      sym_interpolation,
      sym_segment,
  [21] = 6,
    ACTIONS(5), 1,
      anon_sym_LBRACE_LBRACK,
    ACTIONS(7), 1,
      sym_text,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_for,
    STATE(5), 2,
      sym_element,
      aux_sym_source_file_repeat1,
    STATE(10), 2,
      sym_interpolation,
      sym_segment,
  [42] = 6,
    ACTIONS(7), 1,
      sym_text,
    ACTIONS(9), 1,
      anon_sym_LBRACE_LBRACK,
    STATE(2), 1,
      sym_for,
    STATE(18), 1,
      sym_done,
    STATE(5), 2,
      sym_element,
      aux_sym_source_file_repeat1,
    STATE(10), 2,
      sym_interpolation,
      sym_segment,
  [63] = 6,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      anon_sym_LBRACE_LBRACK,
    ACTIONS(18), 1,
      sym_text,
    STATE(2), 1,
      sym_for,
    STATE(5), 2,
      sym_element,
      aux_sym_source_file_repeat1,
    STATE(10), 2,
      sym_interpolation,
      sym_segment,
  [84] = 6,
    ACTIONS(21), 1,
      anon_sym_for,
    ACTIONS(23), 1,
      anon_sym_done,
    ACTIONS(25), 1,
      anon_sym_DOT,
    STATE(9), 1,
      sym_string,
    STATE(22), 1,
      sym_path,
    ACTIONS(27), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [104] = 5,
    ACTIONS(21), 1,
      anon_sym_for,
    ACTIONS(25), 1,
      anon_sym_DOT,
    STATE(9), 1,
      sym_string,
    STATE(22), 1,
      sym_path,
    ACTIONS(27), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [121] = 4,
    ACTIONS(25), 1,
      anon_sym_DOT,
    STATE(9), 1,
      sym_string,
    STATE(27), 1,
      sym_path,
    ACTIONS(27), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [135] = 3,
    ACTIONS(29), 1,
      anon_sym_RBRACK_RBRACE,
    ACTIONS(31), 1,
      anon_sym_DOT,
    STATE(16), 1,
      aux_sym_path_repeat1,
  [145] = 2,
    ACTIONS(35), 1,
      anon_sym_LBRACE_LBRACK,
    ACTIONS(33), 2,
      ts_builtin_sym_end,
      sym_text,
  [153] = 3,
    ACTIONS(27), 1,
      aux_sym_string_token2,
    ACTIONS(37), 1,
      aux_sym_string_token1,
    STATE(25), 1,
      sym_string,
  [163] = 1,
    ACTIONS(39), 3,
      anon_sym_RBRACK_RBRACE,
      anon_sym_in,
      anon_sym_DOT,
  [169] = 2,
    ACTIONS(43), 1,
      anon_sym_LBRACE_LBRACK,
    ACTIONS(41), 2,
      ts_builtin_sym_end,
      sym_text,
  [177] = 2,
    ACTIONS(47), 1,
      anon_sym_LBRACE_LBRACK,
    ACTIONS(45), 2,
      ts_builtin_sym_end,
      sym_text,
  [185] = 3,
    ACTIONS(27), 1,
      aux_sym_string_token2,
    ACTIONS(37), 1,
      aux_sym_string_token1,
    STATE(20), 1,
      sym_string,
  [195] = 3,
    ACTIONS(31), 1,
      anon_sym_DOT,
    ACTIONS(49), 1,
      anon_sym_RBRACK_RBRACE,
    STATE(19), 1,
      aux_sym_path_repeat1,
  [205] = 2,
    ACTIONS(53), 1,
      anon_sym_LBRACE_LBRACK,
    ACTIONS(51), 2,
      ts_builtin_sym_end,
      sym_text,
  [213] = 2,
    ACTIONS(57), 1,
      anon_sym_LBRACE_LBRACK,
    ACTIONS(55), 2,
      ts_builtin_sym_end,
      sym_text,
  [221] = 3,
    ACTIONS(59), 1,
      anon_sym_RBRACK_RBRACE,
    ACTIONS(61), 1,
      anon_sym_DOT,
    STATE(19), 1,
      aux_sym_path_repeat1,
  [231] = 1,
    ACTIONS(59), 2,
      anon_sym_RBRACK_RBRACE,
      anon_sym_DOT,
  [236] = 2,
    ACTIONS(64), 1,
      anon_sym_LBRACE_LBRACK,
    ACTIONS(66), 1,
      sym_text,
  [243] = 1,
    ACTIONS(68), 1,
      anon_sym_RBRACK_RBRACE,
  [247] = 1,
    ACTIONS(29), 1,
      anon_sym_RBRACK_RBRACE,
  [251] = 1,
    ACTIONS(70), 1,
      ts_builtin_sym_end,
  [255] = 1,
    ACTIONS(72), 1,
      anon_sym_in,
  [259] = 1,
    ACTIONS(74), 1,
      anon_sym_RBRACK_RBRACE,
  [263] = 1,
    ACTIONS(76), 1,
      anon_sym_RBRACK_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 21,
  [SMALL_STATE(4)] = 42,
  [SMALL_STATE(5)] = 63,
  [SMALL_STATE(6)] = 84,
  [SMALL_STATE(7)] = 104,
  [SMALL_STATE(8)] = 121,
  [SMALL_STATE(9)] = 135,
  [SMALL_STATE(10)] = 145,
  [SMALL_STATE(11)] = 153,
  [SMALL_STATE(12)] = 163,
  [SMALL_STATE(13)] = 169,
  [SMALL_STATE(14)] = 177,
  [SMALL_STATE(15)] = 185,
  [SMALL_STATE(16)] = 195,
  [SMALL_STATE(17)] = 205,
  [SMALL_STATE(18)] = 213,
  [SMALL_STATE(19)] = 221,
  [SMALL_STATE(20)] = 231,
  [SMALL_STATE(21)] = 236,
  [SMALL_STATE(22)] = 243,
  [SMALL_STATE(23)] = 247,
  [SMALL_STATE(24)] = 251,
  [SMALL_STATE(25)] = 255,
  [SMALL_STATE(26)] = 259,
  [SMALL_STATE(27)] = 263,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_segment, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_segment, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 3, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 3, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_done, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_done, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_segment, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_segment, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_for, 6, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for, 6, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [70] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mytempl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "mytempl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
